require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin_requests_completeds", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AdminRequestsCompleted. As you add validations to AdminRequestsCompleted, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AdminRequestsCompleted.create! valid_attributes
      get admin_requests_completeds_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      admin_requests_completed = AdminRequestsCompleted.create! valid_attributes
      get admin_requests_completed_url(admin_requests_completed)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_requests_completed_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      admin_requests_completed = AdminRequestsCompleted.create! valid_attributes
      get edit_admin_requests_completed_url(admin_requests_completed)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AdminRequestsCompleted" do
        expect {
          post admin_requests_completeds_url, params: { admin_requests_completed: valid_attributes }
        }.to change(AdminRequestsCompleted, :count).by(1)
      end

      it "redirects to the created admin_requests_completed" do
        post admin_requests_completeds_url, params: { admin_requests_completed: valid_attributes }
        expect(response).to redirect_to(admin_requests_completed_url(AdminRequestsCompleted.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AdminRequestsCompleted" do
        expect {
          post admin_requests_completeds_url, params: { admin_requests_completed: invalid_attributes }
        }.to change(AdminRequestsCompleted, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_requests_completeds_url, params: { admin_requests_completed: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_requests_completed" do
        admin_requests_completed = AdminRequestsCompleted.create! valid_attributes
        patch admin_requests_completed_url(admin_requests_completed), params: { admin_requests_completed: new_attributes }
        admin_requests_completed.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the admin_requests_completed" do
        admin_requests_completed = AdminRequestsCompleted.create! valid_attributes
        patch admin_requests_completed_url(admin_requests_completed), params: { admin_requests_completed: new_attributes }
        admin_requests_completed.reload
        expect(response).to redirect_to(admin_requests_completed_url(admin_requests_completed))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        admin_requests_completed = AdminRequestsCompleted.create! valid_attributes
        patch admin_requests_completed_url(admin_requests_completed), params: { admin_requests_completed: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_requests_completed" do
      admin_requests_completed = AdminRequestsCompleted.create! valid_attributes
      expect {
        delete admin_requests_completed_url(admin_requests_completed)
      }.to change(AdminRequestsCompleted, :count).by(-1)
    end

    it "redirects to the admin_requests_completeds list" do
      admin_requests_completed = AdminRequestsCompleted.create! valid_attributes
      delete admin_requests_completed_url(admin_requests_completed)
      expect(response).to redirect_to(admin_requests_completeds_url)
    end
  end
end
