require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/atcs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Atc. As you add validations to Atc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Atc.create! valid_attributes
      get atcs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      atc = Atc.create! valid_attributes
      get atc_url(atc)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_atc_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      atc = Atc.create! valid_attributes
      get edit_atc_url(atc)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Atc" do
        expect {
          post atcs_url, params: { atc: valid_attributes }
        }.to change(Atc, :count).by(1)
      end

      it "redirects to the created atc" do
        post atcs_url, params: { atc: valid_attributes }
        expect(response).to redirect_to(atc_url(Atc.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Atc" do
        expect {
          post atcs_url, params: { atc: invalid_attributes }
        }.to change(Atc, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post atcs_url, params: { atc: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested atc" do
        atc = Atc.create! valid_attributes
        patch atc_url(atc), params: { atc: new_attributes }
        atc.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the atc" do
        atc = Atc.create! valid_attributes
        patch atc_url(atc), params: { atc: new_attributes }
        atc.reload
        expect(response).to redirect_to(atc_url(atc))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        atc = Atc.create! valid_attributes
        patch atc_url(atc), params: { atc: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested atc" do
      atc = Atc.create! valid_attributes
      expect {
        delete atc_url(atc)
      }.to change(Atc, :count).by(-1)
    end

    it "redirects to the atcs list" do
      atc = Atc.create! valid_attributes
      delete atc_url(atc)
      expect(response).to redirect_to(atcs_url)
    end
  end
end
